name: PyInstaller

on:
  push:
    tags: [v*]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip3 install pandas pyinstaller
          pip3 install -e .

      - name: Write secret key
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        run: |
          echo "__import__('os').environ.setdefault('SECRET_KEY', '$env:DJANGO_SECRET_KEY')" > secret.py

      - name: Build static files
        run: |
          npm ci && npm run build

      - name: Collect static files
        run: |
          python3 -m itecha collectstatic --no-input

      - name: Generate executable files
        run: |
          pip3 install --force-reinstall --no-deps .
          pyinstaller --runtime-hook secret.py --hidden-import pandas --collect-submodules whitenoise -F -n itecha ./itecha/__main__.py

      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: itecha-windows
          path: dist/itecha.exe
