name: Staging

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Aliyun FC 2
        run: |
          sudo apt-get install python3-setuptools
          sudo pip3 install -U aliyun-fc2 django pip

      - name: Build static files
        env:
          VUE_APP_ENABLE_CDN: 1
        run: |
          pip3 install .
          npm ci
          npm run build
          ./manage.py collectstatic --no-input

      - name: Deploy with Aliyun FC 2
        env:
          FUNCTION_COMPUTE_ARN: ${{ secrets.FUNCTION_COMPUTE_ARN_STAGING }}
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        run: |
          pip3 install -t dist/fc .[fc]
          rm -rf dist/fc/numpy*
          (cd dist/fc/django/contrib/ && rm -rf gis humanize postgres redirects sitemaps syndication)
          (cd dist/fc/django/contrib/admin/locale/ && find -maxdepth 1 ! -name "zh_Hans" -exec rm -rf '{}' \;)
          du -s dist/fc/*
          ./setup.py deploy
